### ISSUE TITLE
Font size is too small compared to other sans-serif fonts at 13px

### ISSUE THREAD

**Issue by CleverCoder** [theleagueof/league-spartan#41]
I'm seeing an issue that makes it hard to use this font as a replacement for other sans-serif fonts. At 13px, it appears to be occupying around 11px, with the box taking up 12px.

Example code:

```html
        <div style="font-family: Spartan" class="font-div">League Spartan 13px</div>
        <div style="font-family: Helvetica" class="font-div">Helvetica 13px</div>
        <div style="font-family: Arial" class="font-div">Arial 13px</div>
```

```css
@font-face {
    font-family: "Spartan";
    src: url("@/assets/fonts/LeagueSpartan-VF.woff2") format('woff2-variations');
    font-weight: 200 900;
}

.font-div {
    font-size: 13px;
    line-height: normal;
}
```

Result on my MacBook in Chrome:

![image](https://github.com/theleagueof/league-spartan/assets/1012381/c731c911-f75f-4255-bc8f-3d2bc12de42c)
